
------
CREATE GLOBAL TEMPORARY TABLE TEMP_CITY ON COMMIT PRESERVE ROWS AS
SELECT ID, CITYNAME
FROM (SELECT SELECT_TABLE_ALIAS.*, ROWNUM ROW_NUM
      FROM (SELECT ID, CITYNAME FROM CITY ORDER BY ID DESC) SELECT_TABLE_ALIAS
      WHERE ROWNUM <= 20) PAGING_TABLE_ALIAS
WHERE PAGING_TABLE_ALIAS.ROW_NUM >= 11;

TRUNCATE TABLE TEMP_CITY;
DROP TABLE TEMP_CITY PURGE;

------
CREATE TABLE CITY1 AS
SELECT ID, CITYNAME
FROM (SELECT SELECT_TABLE_ALIAS.*, ROWNUM ROW_NUM
      FROM (SELECT ID, CITYNAME FROM CITY ORDER BY ID DESC) SELECT_TABLE_ALIAS
      WHERE ROWNUM <= 20) PAGING_TABLE_ALIAS
WHERE PAGING_TABLE_ALIAS.ROW_NUM >= 11;

TRUNCATE TABLE CITY1;
DROP TABLE CITY1 PURGE;