//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XData.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XData.Data.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete ConcurrencyCheck, Missing value(s) of {0}..
        /// </summary>
        internal static string Constraint_IncompleteConcurrencyCheck {
            get {
                return ResourceManager.GetString("Constraint_IncompleteConcurrencyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert explicit value for AutoIncrement property &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string Constraint_InsertExplicitAutoIncrement {
            get {
                return ResourceManager.GetString("Constraint_InsertExplicitAutoIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert explicit value for Readonly property &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string Constraint_InsertExplicitReadonly {
            get {
                return ResourceManager.GetString("Constraint_InsertExplicitReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicted relationship between entity &apos;{0}&apos;, property(s) {1} and &apos;{2}&apos;, property(s) {3}..
        /// </summary>
        internal static string Constraint_RelationshipConflicted {
            get {
                return ResourceManager.GetString("Constraint_RelationshipConflicted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been deleted by another user..
        /// </summary>
        internal static string DeletedByAnotherUser {
            get {
                return ResourceManager.GetString("DeletedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more rows has been inserted by another user..
        /// </summary>
        internal static string InsertedByAnotherUser {
            get {
                return ResourceManager.GetString("InsertedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expect one but {0} rows affected..
        /// </summary>
        internal static string MultipleRowsAffected {
            get {
                return ResourceManager.GetString("MultipleRowsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expect one but {0} rows found by entity &apos;{1}&apos;, key {2}..
        /// </summary>
        internal static string MultipleRowsFound {
            get {
                return ResourceManager.GetString("MultipleRowsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not an entity property in &apos;{1}&apos;..
        /// </summary>
        internal static string NonEntityProperty {
            get {
                return ResourceManager.GetString("NonEntityProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not an extend property in &apos;{1}&apos;..
        /// </summary>
        internal static string NonExtendProperty {
            get {
                return ResourceManager.GetString("NonExtendProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a field property in &apos;{1}&apos;..
        /// </summary>
        internal static string NonFieldProperty {
            get {
                return ResourceManager.GetString("NonFieldProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a native property in &apos;{1}&apos;..
        /// </summary>
        internal static string NonNativeProperty {
            get {
                return ResourceManager.GetString("NonNativeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change fixed value for property &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string NotChangeFixedValue {
            get {
                return ResourceManager.GetString("NotChangeFixedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change value for Readonly property &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string NotChangeReadonlyValue {
            get {
                return ResourceManager.GetString("NotChangeReadonlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change value for unique key property &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string NotChangeUniqueKeyValue {
            get {
                return ResourceManager.GetString("NotChangeUniqueKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found the entity named &apos;{0}&apos;..
        /// </summary>
        internal static string NotFoundEntity {
            get {
                return ResourceManager.GetString("NotFoundEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found the property named &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string NotFoundProperty {
            get {
                return ResourceManager.GetString("NotFoundProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optimistic concurrency exception at entity &apos;{0}&apos;, key {1}..
        /// </summary>
        internal static string OptimisticConcurrencyException {
            get {
                return ResourceManager.GetString("OptimisticConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;original&apos; does not match the argument &apos;obj&apos;..
        /// </summary>
        internal static string OriginalNotMatch {
            get {
                return ResourceManager.GetString("OriginalNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicted relationship between entity &apos;{0}&apos;, key:{1} and &apos;{2}&apos;, property(s) {3}..
        /// </summary>
        internal static string RelationshipKeyConflicted {
            get {
                return ResourceManager.GetString("RelationshipKeyConflicted", resourceCulture);
            }
        }
    }
}
