//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XData.Data.Schema {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchemaMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchemaMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XData.Data.Schema.SchemaMessages", typeof(SchemaMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting entities &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        public static string ConflictingEntities {
            get {
                return ResourceManager.GetString("ConflictingEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting relatedEntities &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        public static string ConflictingRelatedEntities {
            get {
                return ResourceManager.GetString("ConflictingRelatedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; non-connected..
        /// </summary>
        public static string DirectRelationshipsNonConnected {
            get {
                return ResourceManager.GetString("DirectRelationshipsNonConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity named &apos;{0}&apos; already exists in the schema..
        /// </summary>
        public static string EntityAlreadyExists {
            get {
                return ResourceManager.GetString("EntityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error view &apos;{0}&apos;..
        /// </summary>
        public static string ErrorView {
            get {
                return ResourceManager.GetString("ErrorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos; but was &apos;{1}&apos;..
        /// </summary>
        public static string ExpectedBut {
            get {
                return ResourceManager.GetString("ExpectedBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found the entity named &apos;{0}&apos; in the schema..
        /// </summary>
        public static string NotFoundEntity {
            get {
                return ResourceManager.GetString("NotFoundEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not provide parameter: CustomDataType or DataType..
        /// </summary>
        public static string NotProvideParameter {
            get {
                return ResourceManager.GetString("NotProvideParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relationship named &apos;{0}&apos; already exists in the schema..
        /// </summary>
        public static string RelationshipAlreadyExists {
            get {
                return ResourceManager.GetString("RelationshipAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute relationship is required at ‘{0}’ in ‘{1}’..
        /// </summary>
        public static string RelationshipRequired {
            get {
                return ResourceManager.GetString("RelationshipRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; non-connected..
        /// </summary>
        public static string RelationshipsNonConnected {
            get {
                return ResourceManager.GetString("RelationshipsNonConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaired parenthesis in &apos;{0}&apos;..
        /// </summary>
        public static string UnpairedParenthesis {
            get {
                return ResourceManager.GetString("UnpairedParenthesis", resourceCulture);
            }
        }
    }
}
